SELECT ARTISTID, NAME FROM ARTIST WHERE NAME IN ('AC/DC', 'Aerosmith');
SELECT ALBUM.TITLE FROM ALBUM WHERE ARTISTID IN (SELECT ARTISTID FROM ARTIST WHERE NAME IN ('AC/DC', 'Aerosmith'));
SELECT ALBUM.TITLE FROM ALBUM WHERE ALBUMID < (SELECT ARTISTID FROM ARTIST WHERE NAME LIKE 'Aerosmith');
SELECT T.NAME FROM TRACK T WHERE T.ALBUMID IN (SELECT AL.ALBUMID FROM ALBUM AL WHERE AL.ARTISTID IN (SELECT AR.ARTISTID FROM ARTIST AR WHERE AR.NAME = 'Aerosmith'));


/*TRACKS THAT ARE IN PLAYLISTS WITH AC/DC TRACKS */
SELECT    NAME        FROM TRACK          WHERE   TRACKID   IN 
(SELECT   TRACKID     FROM PLAYLISTTRACK  WHERE PLAYLISTID IN
(SELECT PLAYLISTID    FROM PLAYLISTTRACK  WHERE TRACKID IN 
(SELECT T.TRACKID     FROM TRACK T        WHERE T.ALBUMID IN 
(SELECT AL.ALBUMID    FROM ALBUM AL       WHERE AL.ARTISTID IN 
(SELECT AR.ARTISTID   FROM ARTIST AR      WHERE AR.NAME = 'AC/DC')))))
/*TRACKS NOT BY AC/DC */
AND TRACKID IN
(SELECT T.TRACKID     FROM TRACK T        WHERE T.ALBUMID NOT IN 
(SELECT AL.ALBUMID    FROM ALBUM AL       WHERE AL.ARTISTID IN 
(SELECT AR.ARTISTID   FROM ARTIST AR      WHERE AR.NAME = 'AC/DC')))
GROUP BY NAME ORDER BY NAME;


SELECT NAME FROM TRACK WHERE TRACKID IN (SELECT TRACKID FROM PLAYLISTTRACK WHERE PLAYLISTID IN
(SELECT PLAYLISTID FROM PLAYLISTTRACK WHERE TRACKID IN 
(SELECT T.TRACKID FROM TRACK T WHERE T.ALBUMID IN 
(SELECT AL.ALBUMID FROM ALBUM AL WHERE AL.ARTISTID IN 
(SELECT AR.ARTISTID  FROM ARTIST AR WHERE AR.NAME = 'AC/DC')))));